name: Continuous Integration

on: push

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - run: yarn install
      - run: yarn firebase emulators:exec --only database "yarn test --watchAll=false"
      - run: yarn build
